[project]
name = "y-rig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "msgspec>=0.21.1",
    "nxt-core>=0.18.1",
]

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "debug"}
]
lint = [
    "ty>=0.0.14",
    "ruff>=0.14.14",
    "maya-stubs>=0.4.2",
    "numpy>=2.4.1",
    "qt-py>=2.0.2",
]
debug = ["debugpy>=1.8.19"]
maya = [
    {include-group = "debug"}
]

[tool.ruff]
line-length = 100
exclude = ["third_party", "maya-setup.py"]

[tool.ruff.lint]
extend-select = ["ANN"]
ignore = ["ANN204", "ANN002", "ANN003", "F841"]

[tool.ruff.lint.per-file-ignores]
"shifter/*" = ["ANN"]

[tool.pyright]
extraPaths = [
    "/usr/autodesk/ApplicationPlugins/ngskintools2/Contents/scripts",
    "third_party/mgear/release/scripts/",
    "src"
]
ignore = ["third_party"]
typeCheckingMode = "standard"
reportMissingModuleSource = "information"

[tool.ty.environment]
extra-paths = [
    "/usr/autodesk/ApplicationPlugins/ngskintools2/Contents/scripts",
    "third_party/mgear/release/scripts/",
    "src"
]

[tool.ty.src]
exclude = ["third_party"]

[tool.ty.analysis]
allowed-unresolved-imports = ["ngSkinTools2.**"]
